/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '10/27/16 4:22 PM' with Gradle 2.14.1
 *
 * @author User, @date 10/27/16 4:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
